name: MagicWorldGuard
version: '${version}'

main: org.psyrioty.magicWorldGuard.MagicWorldGuard
api-version: '26.2'
load: POSTWORLD
depend: [WorldGuard, FastAsyncWorldEdit]

commands:
  region:
    description: MagicWorldGuard plugin commands
    usage: /region
    aliases:
      - rg
      - regions
    permission: group.default
    permission-message: "Not permission"
